# Generated by Django 2.0.13 on 2020-07-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
    ]
